config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: { sessions: "admins/sessions"}
  resources :acessos
  resources :clientes

  get "htmltopdf" => 'clientes#htmltopdf'
  get "email_send" => 'clientes#email_send'
  get "relatorio_acessos" => 'acessos#relatorio_acessos'
  get "relatorio_clientes" => 'clientes#relatorio_clientes'

  root 'acessos#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	extend FriendlyId
	friendly_id :nome, use: [:slugged, :finders]
	has_many :acessos, dependent: :destroy

	validates :nome, format: { with: /\A[a-z A-Z]+\z/, message: "Insira apenas letras e espaços no nome" }
	validates :cpf, format: { with: /\A\d{3}.\d{3}.\d{3}-\d{2}\z/, message: "Insira o CPF no formato \"999.999.999-99\"" }
	scope :recent_qtd_acesso, -> { order("qtd_acesso DESC") }
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
	before_action :authenticate_admin!

	def index
		@clientes = Cliente.paginate(:page => params[:page], :per_page => 5).recent_qtd_acesso.all

		respond_to do |format|
	      	format.html
	      	format.xml { render :xml => @clientes }
	      	format.json { render :json => @clientes }
    	end
	end

	def show
		@cliente = Cliente.friendly.find(params[:id])

		respond_to do |format|
	      	format.html
	      	format.xml { render :xml => @cliente.to_xml }
	      	format.json { render :json => @cliente.to_json }
    	end
	end

	def new
		@cliente = Cliente.new
	end

	def edit
		@cliente = Cliente.friendly.find(params[:id])
	end

	def create
		# Cria hash com os valores default, e junta com os parâmetros passados pelo POST
		defaults = {:qtd_acesso => 0, :bonus_acumulado => 0, :horas_gratis => 0}
		valores = defaults.merge(cliente_params)

		@cliente = Cliente.new(valores)
		if @cliente.save
			flash[:aviso] = "insert"
	    	redirect_to '/clientes'
	    else
	      render 'new'
	    end
	end

	def update
		@cliente = Cliente.friendly.find(params[:id])
 
		if @cliente.update(cliente_params)
			flash[:aviso] = "update"
			redirect_to '/clientes'
		else
			render 'edit'
		end
	end

	def destroy
		@cliente = Cliente.friendly.find(params[:id])
	    @cliente.destroy
	 
	 	flash[:aviso] = "delete"
	    redirect_to '/clientes'
	end

	# Testes do HyPDF
	def htmltopdf
		hypdf = HyPDF.htmltopdf(
		    '<html><body><h1>Teste HyPDF</h1></body></html>',
		    test: true
		)

		send_data(hypdf[:pdf], filename: 'hypdf_test.pdf', type: 'application/pdf')
	end

	def relatorio_clientes
		html = %Q{
			<html>
			<head>
				<meta charset="UTF-8">
				<title>Relatório dos Clientes cadastrados</title>

				<style>
					table {
						width: 100%;
					}

					table, tr, th, td {
						border: 1px solid black;
						border-collapse: collapse;
					}
				</style>
			</head>
			<body>
				<br>
				<h1>Relatório de todos os Clientes da LAN</h1>

				<table style="">
					<thead>
						<tr>
							<th>Nome</th>
							<th>CPF</th>
							<th>E-mail</th>
							<th>Data de Nascimento</th>
							<th>Quantidade de Acessos</th>
						</tr>
				    </thead>

				    <tbody>
		}

		Cliente.recent_qtd_acesso.all.each do |cliente|
			html << %Q{
				<tr>
		    		<td class="vert-align">#{cliente.nome}</td>
		    		<td class="vert-align">#{cliente.cpf}</td>
		    		<td class="vert-align">#{cliente.email} h</td>
		    		<td class="vert-align">#{cliente.data_nasc.to_time.strftime("%d/%m/%Y") }</td>
		    		<td class="vert-align">#{cliente.qtd_acesso}</td>
		    	</tr>
			}
		end

		html << %Q{
				</tbody>
			</table>
		</body>
		</html>
		}

		hypdf = HyPDF.htmltopdf(
		    html,
		    test: true
		)

		send_data(hypdf[:pdf], filename: 'relatorio_clientes.pdf', type: 'application/pdf')
	end

	# Testes do Postmark
	def email_send
		ClienteMailer.welcome_message.deliver!
		render plain: "E-mail enviado com sucesso!"
	end

	# Privates
	private
		def cliente_params
			params.require(:cliente).permit(:nome, :cpf, :data_nasc, :email)
		end
end

app/helpers/clientes_helper.rb
module ClientesHelper
	def alert_title(job)
		retorno = "";
		if job == "insert"
		    return %Q{
		    	<div class='alert alert-success aviso-cadastro-alert' role='alert'>
		    		<span class='fa fa-check-circle-o' aria-hidden='true'></span> Cliente cadastrado com sucesso!
		    	</div>}.html_safe
		end
		if job == "update"
		    return %Q{
		    	<div class='alert alert-success aviso-cadastro-alert' role='alert'>
		    		<span class='fa fa-check-circle-o' aria-hidden='true'></span> Cliente atualizado com sucesso.
		    	</div>}.html_safe
		end
		if job == "delete"
		    return %Q{
		    	<div class='alert alert-warning aviso-cadastro-alert' role='alert'>
		    		<span class='fa fa-times-circle-o' aria-hidden='true'></span> Cliente deletado com sucesso.
		    	</div>}.html_safe
		end
	end
end

app/views/clientes/_form.html.erb
<%= form_for @cliente, :html => { :class => "col-md-5 col-centered" } do |f| %>

	<div class="form-group">
		<%= f.label :nome, "Nome:", :class => 'control-label' %><br>
    	<%= f.text_field :nome, :class => 'form-control', :required => 'required' %>
	</div>

	<div class="form-group">
		<%= f.label :cpf, "CPF:", :class => 'control-label' %><br>
    	<%= f.text_field :cpf, :class => 'form-control', :required => 'required' %>
	</div>

	<div class="form-group">
		<%= f.label :email, "E-mail:", :class => 'control-label' %><br>
    	<%= f.email_field :email, :class => 'form-control', :required => 'required' %>
	</div>

	<div class="form-group">
		<%= f.label :data_nasc, "Data de Nascimento:", :class => 'control-label' %><br>
    	<%= f.date_field :data_nasc, :class => 'form-control', :required => 'required' %>
	</div>

	<%= f.submit "Enviar", :class => 'btn btn-primary' %>

<% end %>

app/views/clientes/_validation.html.erb
<% if @cliente.errors.any? %>
<div class="row">
	<div class="col-md-5 col-centered">
		<div id="error_explanation" class="panel panel-danger">
			<div class="panel-heading">
				<%= pluralize(@cliente.errors.count, "erro") %>
				no formulário:
			</div>

			<ul class="list-group">
				<% @cliente.errors.each do |key, value| %>
					<li class="list-group-item"><%= value %></li>
				<% end %>
			</ul>
		</div>
	</div>
</div>
<% end %>

app/views/clientes/edit.html.erb
<%= render 'validation' %>

<h2 class="text-center">Atualizar Cliente - <%= @cliente.id %></h2>

<div class="row">
	<%= render 'form' %>
</div>

app/views/clientes/index.html.erb
<div class="row aviso-cadastro">
  <% if flash[:aviso] %>
        <%= alert_title(flash[:aviso]) %>
  <% end %>
  
  <h2 class="text-center">Clientes Cadastrados</h2>
</div>

<br>

<div class="row">
  <div class="row">
    <div class="col-md-5">
    </div>
    <div class="col-md-7">
      <a href="/clientes/new" class="btn btn-sm btn-primary pull-right"><span class="fa fa-external-link"></span> Novo</a>
    </div>
  </div>

  <br>

  <table class="col-md-12 table table-bordered table-striped">
    <thead>
      <th>Nome</th>
      <th>CPF</th>
      <th>E-mail</th>
      <th>Data de Nascimento</th>
      <th>Quantidade de Acessos</th>
      <th>Bônus Acumulado</th>
      <th>Horas Grátis Disponíveis</th>
      <th>Ações</th>
    </thead>

    <tbody>
      <% @clientes.each do |cliente| %>
      <tr>
        <td class="vert-align"><%= link_to cliente.nome, cliente_path(cliente) %></td>
        <td class="vert-align"><%= cliente.cpf %></td>
        <td class="vert-align"><%= cliente.email %></td>
        <td class="vert-align"><%= cliente.data_nasc.to_time.strftime("%d/%m/%Y") %></td>
        <td class="vert-align"><%= cliente.qtd_acesso %></td>
        <td class="vert-align"><%= cliente.bonus_acumulado %></td>
        <td class="vert-align"><%= cliente.horas_gratis %></td>
        <td class="vert-align">
          <%= link_to edit_cliente_path(cliente),
              class: 'btn btn-sm btn-default' do %>
            <span class="fa fa-pencil"></span>
          <% end %>

          <%= link_to cliente_path(cliente),
              method: :delete,
              data: { confirm: 'Tem certeza que deseja remover esse Cliente?' },
              class: 'btn btn-sm btn-danger' do %>
            <span class="fa fa-times"></span>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div class="row">
    <div class="col-md-12 digg_pagination">
      <%= will_paginate @clientes %>
    </div>
  </div>

  <div class="row">
      <div class="col-md-12">
        <a href="/relatorio_clientes" class="btn btn-default">
          <span class="fa fa-list-alt"></span>&nbsp; Gerar Relatório dos Clientes cadastrados
        </a>
      </div>
    </div>
</div>

<script>
  var aviso = $('.aviso-cadastro-alert');

  if (aviso.length) {
    aviso.fadeIn(500).
      delay(5000).
      fadeOut(500);
  }  
</script>

app/views/clientes/new.html.erb
<%= render 'validation' %>

<h2 class="text-center">Cadastrar Cliente</h2>

<div class="row">
	<%= render 'form' %>
</div>

app/views/clientes/show.html.erb
<h2 class="text-center">Dados do Cliente - <%= @cliente.id %></h2>

<br>

<style>
	.show-label {
		text-align: left !important;
	}
</style>

<div class="row">
	<form action="#" class="form-horizontal col-centered col-md-6">
		<div class="form-group row">
			<label class="col-sm-5 control-label show-label">Nome:</label>
			<div class="col-sm-7">
				<p class="form-control-static"><%= @cliente.nome %></p>
			</div>
		</div>
		
		<div class="form-group row">
			<label class="col-sm-5 control-label show-label">CPF:</label>
			<div class="col-sm-7">
				<p class="form-control-static"><%= @cliente.cpf %></p>
			</div>
		</div>
		
		<div class="form-group row">
			<label class="col-sm-5 control-label show-label">E-mail:</label>
			<div class="col-sm-7">
				<p class="form-control-static"><%= @cliente.email %></p>
			</div>
		</div>
		
		<div class="form-group row">
			<label class="col-sm-5 control-label show-label">Data de Nascimento:</label>
			<div class="col-sm-7">
				<p class="form-control-static"><%= @cliente.data_nasc.to_time.strftime("%d/%m/%Y") %></p>
			</div>
		</div>
		
		<div class="form-group row">
			<label class="col-sm-5 control-label show-label">Quantidade de Acessos:</label>
			<div class="col-sm-7">
				<p class="form-control-static"><%= @cliente.qtd_acesso %></p>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-5 control-label show-label">Bonus Acumulado:</label>
			<div class="col-sm-7">
				<p class="form-control-static"><%= @cliente.bonus_acumulado %></p>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-5 control-label show-label">Horas Grátis disponíveis:</label>
			<div class="col-sm-7">
				<p class="form-control-static"><%= @cliente.horas_gratis %></p>
			</div>
		</div>

		<div class="form-group row">
			<label class="col-sm-5 control-label show-label">Cadastrado desde:</label>
			<div class="col-sm-7">
				<p class="form-control-static">
					<%= @cliente.created_at.to_time.strftime("%d/%m/%Y") %>
				</p>
			</div>
		</div>

		<div class="form-group row">
			<div class="col-sm-2">
				<%= link_to edit_cliente_path(@cliente),
					class: 'btn btn-default' do %>
					<span class="fa fa-pencil"></span> Editar
				<% end %>
			</div>

			<div class="col-sm-2">
				<%= link_to cliente_path(@cliente),
	                method: :delete,
	                data: { confirm: 'Tem certeza que deseja remover esse Cliente?' },
	                class: 'btn btn-danger' do %>
	              <span class="fa fa-times"></span> Excluir
	            <% end %>
			</div>
		</div>

	</form>
</div>