config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: { sessions: "admins/sessions"}
  resources :acessos
  resources :clientes

  get "htmltopdf" => 'clientes#htmltopdf'
  get "email_send" => 'clientes#email_send'
  get "relatorio_acessos" => 'acessos#relatorio_acessos'
  get "relatorio_clientes" => 'clientes#relatorio_clientes'

  root 'acessos#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Landafrad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if admin_signed_in? %>
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Alternar</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">Stuna que eu mato</a>
		</div>

		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><a href="/acessos">Acessos</a></li>
				<li><a href="/clientes">Clientes</a></li>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				<li>
					<a href="admins/sign_out" data-method="delete" rel="nofollow">Logout</a>
				</li>
			</ul>
		</div>
	</div>
</nav>
<% end %>

<div class="container" style="margin-bottom: 85px">
<%= yield %>
</div>

<% if admin_signed_in? %>
<footer class="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<p class="text-muted">© 2015 - Todos os Direitos Reservados</p>
			</div>

			<div class="col-md-6 text-right">
				<p class="text-muted">Desenvolvimento Ágil com Ferramenta RAD | <a href="https://github.com/evandrohcm/LanDAFRAD" target="_blank"><strong>Lan House - Stuna que eu mato</strong></a></p>
			</div>
		</div>
	</div>
</footer>
<% end %>

</body>
</html>